project_id = "qduhlfqsgumuhkjjyutc"

[functions.sync-easysales]
verify_jwt = false

[functions.sync-costs]
verify_jwt = false

[functions.recalculate-costs]
verify_jwt = false

[functions.resync-orders]
verify_jwt = false
